#!/usr/bin/env bash

# Change to this script's folder
cd "${0%/*}"

# Load the library into the Bash environment
. ../ansi

ansi_blue
echo "This is blue"
echo "Blue and blue and more blue."
ansi_italic
echo "The colors $(../ansi_bold)don't automatically reset$(../ansi_normal)."
ansi_resetForeground
echo "The color was reset, but italics remain at this point."
ansi_plain

echo "Back to normal."

echo "This is $(ansi_inverse)inverse$(ansi_noInverse) text."

# You can use the command as well, but this no longer runs ansi
# as an external binary. It uses the function and saves time since
# it no longer uses a subshell. As proof, we unset the PATH variable
# before running ANSI so you know it's running a function.
PATH="" ../ansi --green "This is running a function"

